baseURL = 'https://innovationweb.netlify.app/'
languageCode = 'en-us'
title = 'Innovation Home'
theme = 'PaperMod'


[params]
  ShowShareButtons = true
  ShowToc = false
  ShowAuthor = true
  showPostNavLinks = true
  showReadingTime = true
  showToc = true
  showPostThumbnails = true
  showBreadCrumbs = true
  defaultTheme = "light"
  mainSections = [ "projects", "information"]
  hideFooter = true
  disableThemeToggle= true
  

  [params.homeInfoParams]
 Title = "Welcome to GSSN Innovation"
 Content = "Empowering Medical Innovation through Design and Technology."
  
  
 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "mailto:jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "information"
    name = "Information"
    url = "/Information/"
    weight = 1
    
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/Projects/"
    weight = 2

  [[menu.main]]
  identifier = "team"
  name = "Team"
  url = "/team/"
  weight = 4

 [[menu.main]]
 identifier = "paper"
  name = "Papers"
 url = "/Papers/"
weight = 3
