baseURL = 'https://innovationweb.netlify.app/'
languageCode = 'en-us'
title = 'Innovation Home'
theme = 'PaperMod'


[params]
  ShowShareButtons = false
  ShowAuthor = true
  showPostNavLinks = true
  showReadingTime = false
  showToc = true
  showPostThumbnails = true
  showBreadCrumbs = false
  defaultTheme = "light"
  mainSections = ["information"]
  hideFooter = true
  disableThemeToggle= true
  showSectionPages = true
  
  [params.label]
icon = "/images/final.png"
iconHeight = 50
text = " "

[params.assets]
favicon = "/icons/favicon.ico"
favicon16x16 = "/icons/favicon-16x16.png"
favicon32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"

  [params.homeInfoParams]
 Title = "GSSN INNOVATION"
Content = """{{< typeit 
speed="50"
  >}}
Empowering Medical Innovation through Design and Technology.
{{< /typeit >}}"""
  
  
 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "mailto:jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "information"
    name = "Information"
    url = "/Information/"
    weight = 1
    

  [[menu.main]]
  identifier = "team"
  name = "Team"
  url = "/team/"
  weight = 10



  [[menu.main]]
    identifier = "medtech-modeling-series"
    name = "Medtech-Modeling"
    url = "/medtech-modeling-series/"
    weight = 2
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
