baseURL = 'https://innovationweb.netlify.app/'
languageCode = 'en-us'
title = 'Innovation Home'
theme = 'PaperMod'


[params]
  ShowShareButtons = true
  ShowToc = false
  showPostNavLinks = true
  showReadingTime = true
  showToc = true
  showPostThumbnails = true
  showBreadCrumbs = true
  defaultTheme = "auto"
  mainSections = ["Events", "Projects"]
  
  [params.homeInfoParams]
 Title = "Welcome to GSSN Innovation"
 Content = "Empowering Medical Innovation through Design and Technology."
  
  
 [[params.socialIcons]]
  name = "github"
  url = "https://github.com/NischalDawadi"


[[params.socialIcons]]
    name = "email"
    url = "https://gmail.com/jamesdawadi13@gmail.com"

  [[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/@dawadinischal"

[menu]
  [[menu.main]]
    identifier = "Information"
    name = "Information"
    url = "/Information/"
    weight = 1

  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/Projects/"
    weight = 2
